CREATE TABLE IF NOT EXISTS player(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(100),
uuid VARCHAR(40),
PRIMARY KEY ( id )
);

CREATE TABLE IF NOT EXISTS perm_group(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(100),
PRIMARY KEY ( id )
);

CREATE TABLE IF NOT EXISTS perm(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(100),
PRIMARY KEY ( id )
);